import {Varta  } from "next/font/google";
import "./globals.css";

const varta = Varta({
  
  subsets: ["latin"],
});



export const metadata = {
  title: " Next App",
  description: "Generated by Heshan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${varta.className} `}>
        <div className="wrapper">
        <div className="row"> <h1>global header</h1></div>
        {children}
        <div className="row"> <h1>global footer</h1></div>
        </div>
      </body>
    </html>
  );
}
